# Generated by Django 6.0.7 on 2026-07-27 10:47

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('role', models.CharField(blank=True, choices=[('DG', 'Directeur Général'), ('ADCH', 'Gestion du Capital Humain'), ('CDV', 'Chef Division Ventes'), ('CDM', 'Chef Division Marketing'), ('CDN', 'Chef Division Numérique'), ('COMMERCIAL', 'Commercial'), ('COMPTABLE_GENERAL', 'Comptable Général'), ('ASSISTANT_COMPTABLE', 'Assistant Comptable'), ('DEVELOPPEUR', 'Développeur'), ('RDW', 'Responsable Développement Web'), ('RSI', "Responsable Systèmes d'Information"), ('VIP', 'Chef Division Visibilité, Infrastructure et Production'), ('RESPONSABLE_VISIBILITE', 'Responsable Visibilité')], max_length=30, null=True, verbose_name='fonction')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='photo de profil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('role__in', ['CDV', 'RESPONSABLE_VISIBILITE', 'VIP', 'DG', 'ADCH', 'COMPTABLE_GENERAL', 'RDW', 'CDM', 'RSI', 'CDN'])), fields=('role',), name='unique_role_holder')],
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
    ]
