# Generated by Django 6.0.7 on 2026-07-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_role_holder',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrateur'), ('DG', 'Directeur Général'), ('ADCH', 'Gestion du Capital Humain'), ('CDV', 'Chef Division Ventes'), ('CDM', 'Chef Division Marketing'), ('CDN', 'Chef Division Numérique'), ('COMMERCIAL', 'Commercial'), ('COMPTABLE_GENERAL', 'Comptable Général'), ('ASSISTANT_COMPTABLE', 'Assistant Comptable'), ('DEVELOPPEUR', 'Développeur'), ('RDW', 'Responsable Développement Web'), ('RSI', "Responsable Systèmes d'Information"), ('VIP', 'Chef Division Visibilité, Infrastructure et Production'), ('RESPONSABLE_VISIBILITE', 'Responsable Visibilité')], max_length=30, null=True, verbose_name='fonction'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['VIP', 'RESPONSABLE_VISIBILITE', 'RDW', 'DG', 'ADCH', 'COMPTABLE_GENERAL', 'RSI', 'CDM', 'CDN', 'CDV'])), fields=('role',), name='unique_role_holder'),
        ),
    ]
