# Generated by Django 6.0.7 on 2026-07-27 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_remove_user_unique_role_holder_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CLIENT', 'Client'), ('PARTENAIRE', 'Partenaire')], max_length=20, verbose_name='type de contact')),
                ('entity_type', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('PME', 'PME'), ('INSTITUTION', 'Institution'), ('GRANDE_ENTREPRISE', 'Grande Entreprise')], max_length=20, verbose_name='type de prospect')),
                ('name', models.CharField(max_length=150, verbose_name='nom complet')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='entreprise / institution')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name="secteur d'activité")),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('stage', models.CharField(choices=[('PRISE_DE_CONTACT', 'Prise de Contact'), ('QUALIFICATION', 'Qualification'), ('CIBLAGE_MARKETING', 'Ciblage Marketing'), ('CHIFFRAGE_OFFRE', 'Chiffrage & Offre'), ('CONVERSION_CLIENT', 'Conversion Client')], default='PRISE_DE_CONTACT', max_length=30, verbose_name='étape')),
                ('score', models.PositiveSmallIntegerField(default=20, verbose_name='score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_role_holder',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['CDN', 'COMPTABLE_GENERAL', 'VIP', 'RSI', 'RESPONSABLE_VISIBILITE', 'RDW', 'DG', 'CDV', 'CDM', 'ADCH'])), fields=('role',), name='unique_role_holder'),
        ),
        migrations.AddField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='commercial assigné'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par'),
        ),
    ]
