# Generated by Django 6.0.7 on 2026-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_contact_remove_user_unique_role_holder_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_role_holder',
        ),
        migrations.AlterField(
            model_name='contact',
            name='stage',
            field=models.CharField(choices=[('PRISE_DE_CONTACT', 'Prise de Contact'), ('QUALIFICATION', 'Qualification'), ('ECHANGES', 'Échanges'), ('CHIFFRAGE_OFFRE', 'Chiffrage & Offre'), ('CONVERSION_CLIENT', 'Conversion Client')], default='PRISE_DE_CONTACT', max_length=30, verbose_name='étape'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['ADCH', 'VIP', 'CDN', 'COMPTABLE_GENERAL', 'RSI', 'DG', 'RESPONSABLE_VISIBILITE', 'RDW', 'CDM', 'CDV'])), fields=('role',), name='unique_role_holder'),
        ),
    ]
