# Generated by Django 6.0.7 on 2026-07-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_remove_user_unique_role_holder_alter_contact_stage_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_role_holder',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='source du prospect'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['CDV', 'RDW', 'DG', 'RESPONSABLE_VISIBILITE', 'COMPTABLE_GENERAL', 'ADCH', 'CDN', 'CDM', 'VIP', 'RSI'])), fields=('role',), name='unique_role_holder'),
        ),
    ]
