# Generated by Django 6.0.7 on 2026-07-28 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_remove_user_unique_role_holder_contact_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('CALL', 'Appel'), ('MEETING', 'Réunion'), ('EMAIL', 'Email')], max_length=20, verbose_name="type d'échange")),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='objet')),
                ('description', models.TextField(blank=True, verbose_name='note')),
                ('occurred_at', models.DateTimeField(verbose_name="date de l'échange")),
                ('attachment', models.FileField(blank=True, null=True, upload_to='interaction_attachments/', verbose_name='pièce jointe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_role_holder',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['ADCH', 'CDM', 'CDN', 'CDV', 'COMPTABLE_GENERAL', 'DG', 'RDW', 'RESPONSABLE_VISIBILITE', 'RSI', 'VIP'])), fields=('role',), name='unique_role_holder'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.contact', verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par'),
        ),
    ]
