# Generated by Django 6.0.7 on 2026-07-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_interaction_remove_user_unique_role_holder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CALL', 'Appel'), ('MEETING', 'Réunion')], max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='intitulé')),
                ('starts_at', models.DateTimeField(verbose_name='date et heure')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='lieu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.contact', verbose_name='contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='intitulé')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('done', models.BooleanField(default=False, verbose_name='terminée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.contact', verbose_name='contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
            ],
            options={
                'ordering': ['done', 'due_date'],
            },
        ),
    ]
