# Generated by Django 6.0.7 on 2026-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='converti le'),
        ),
    ]
