# Generated by Django 6.0.7 on 2026-07-30 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contact_converted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('CONTACT', 'Suivi contact'), ('PRESTATION', 'Tâche de prestation')], default='CONTACT', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.contact', verbose_name='contact'),
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='intitulé')),
                ('deadline', models.DateField(verbose_name='échéance')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='core.division', verbose_name='division')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.prestation', verbose_name='prestation'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom du projet')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('deadline', models.DateField(verbose_name='échéance globale')),
                ('status', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('A_TRAITER', 'À traiter'), ('EN_COURS', 'En cours'), ('EN_VALIDATION_INTERNE', 'En validation interne'), ('EN_VALIDATION_CLIENT', 'En validation client'), ('EN_CORRECTION', 'En correction'), ('PRET_POUR_EXECUTION', 'Prêt pour exécution'), ('LIVRE', 'Livré'), ('CLOTURE', 'Clôturé'), ('BLOQUE', 'Bloqué')], default='NOUVEAU', max_length=30, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.contact', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prestation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='core.project', verbose_name='projet'),
        ),
    ]
