# Generated by Django 6.0.7 on 2026-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_division_task_task_type_alter_task_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('PROSPECT', 'Prospect'), ('CLIENT', 'Client'), ('PARTENAIRE', 'Partenaire'), ('INTERNE', 'Interne (Agence)')], max_length=20, verbose_name='type de contact'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='deadline',
            field=models.DateTimeField(verbose_name='échéance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(verbose_name='échéance globale'),
        ),
    ]
