# Generated by Django 6.0.7 on 2026-07-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contact_contact_type_alter_prestation_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Élevée'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible')], default='MEDIUM', max_length=10, verbose_name='priorité'),
        ),
    ]
