# Generated by Django 6.0.7 on 2026-07-30 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='core.division', verbose_name='division'),
        ),
    ]
