# Generated by Django 6.0.7 on 2026-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_prestation_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="montant de l'acompte"),
        ),
        migrations.AddField(
            model_name='project',
            name='requires_deposit',
            field=models.BooleanField(default=False, verbose_name='acompte requis'),
        ),
    ]
