# Generated by Django 6.0.7 on 2026-07-31 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_project_budget_project_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='converti en projet le'),
        ),
        migrations.AddField(
            model_name='project',
            name='kind',
            field=models.CharField(choices=[('OPPORTUNITE', 'Opportunité'), ('PROJET', 'Projet')], default='PROJET', max_length=15, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='project',
            name='probability',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='probabilité (%)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='budget'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='échéance globale'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('A_TRAITER', 'À traiter'), ('EN_COURS', 'En cours'), ('EN_VALIDATION_INTERNE', 'En validation interne'), ('EN_VALIDATION_CLIENT', 'En validation client'), ('EN_CORRECTION', 'En correction'), ('PRET_POUR_EXECUTION', 'Prêt pour exécution'), ('LIVRE', 'Livré'), ('CLOTURE', 'Clôturé'), ('BLOQUE', 'Bloqué'), ('PERDUE', 'Perdue')], default='NOUVEAU', max_length=30, verbose_name='statut'),
        ),
    ]
