# Generated by Django 6.0.7 on 2026-08-04 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project_converted_at_project_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.division', verbose_name='division'),
        ),
    ]
