# Generated by Django 6.0.7 on 2026-08-04 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('CONTACT', 'Contact'), ('PROJECT', 'Projet')], default='CONTACT', max_length=10, verbose_name='rattaché à')),
                ('document_type', models.CharField(choices=[('DEVIS', 'Devis'), ('FACTURE_PROFORMA', 'Facture proforma'), ('FACTURE', 'Facture'), ('CONTRAT', 'Contrat'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='type de document')),
                ('file', models.FileField(upload_to='documents/', verbose_name='fichier')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='libellé')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='ajouté le')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.contact', verbose_name='contact')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project', verbose_name='projet')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='ajouté par')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
