# Generated by Django 6.0.7 on 2026-08-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('CONTRAT', 'Contrat'), ('CONVENTION', 'Convention'), ('DEVIS', 'Devis'), ('FACTURE', 'Facture'), ('BRIEF', 'Brief'), ('FICHE_BAT', 'Fiche BAT'), ('VISUEL', 'Visuel'), ('PRESENTATION', 'Présentation'), ('LIVRABLE_FINAL', 'Livrable final'), ('JUSTIFICATIF', 'Justificatif'), ('RAPPORT', 'Rapport')], max_length=20, verbose_name='type de document'),
        ),
    ]
