# Generated by Django 6.0.7 on 2026-08-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrateur'), ('DG', 'Directeur Général'), ('ADCH', 'Gestion du Capital Humain'), ('CDV', 'Chef Division Ventes'), ('CDM', 'Chef Division Marketing'), ('CDN', 'Chef Division Numérique'), ('COMMERCIAL', 'Commercial'), ('CHARGE_PARTENARIAT', 'Chargé(e) de Partenariat'), ('GRAPHISTE', 'Graphiste'), ('COMPTABLE_GENERAL', 'Comptable Général'), ('ASSISTANT_COMPTABLE', 'Assistant Comptable'), ('DEVELOPPEUR', 'Développeur'), ('RDW', 'Responsable Développement Web'), ('RSI', "Responsable Systèmes d'Information"), ('VIP', 'Chef Division VIP'), ('RESPONSABLE_VISIBILITE', 'Responsable Visibilité')], max_length=30, null=True, verbose_name='fonction'),
        ),
    ]
