# Generated by Django 6.0.7 on 2026-08-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_task_description_priority_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('A_VALIDER', 'À valider'), ('VALIDE', 'Validé'), ('PIECE_JOINTE', 'Pièce jointe')], default='PIECE_JOINTE', max_length=20, verbose_name='statut'),
        ),
    ]
