# Generated by Django 6.0.7 on 2026-08-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='next_followup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='prochaine relance'),
        ),
        migrations.AddField(
            model_name='project',
            name='deposit_received',
            field=models.BooleanField(default=False, verbose_name='acompte reçu'),
        ),
        migrations.AddField(
            model_name='project',
            name='final_payment_received',
            field=models.BooleanField(default=False, verbose_name='paiement final reçu'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('CALL', 'Appel'), ('MEETING', 'Réunion'), ('EMAIL', 'Email'), ('MESSAGE', 'Message')], max_length=20, verbose_name="type d'échange"),
        ),
    ]
