# Generated by Django 6.0.7 on 2026-08-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='stage',
            field=models.CharField(blank=True, choices=[('PRISE_DE_CONTACT', 'Prise de Contact'), ('QUALIFICATION', 'Qualification'), ('ECHANGES', 'Échanges'), ('CHIFFRAGE_OFFRE', 'Chiffrage & Offre'), ('CONVERSION_CLIENT', 'Conversion Client')], max_length=30, null=True, verbose_name="étape du contact au moment de l'échange"),
        ),
    ]
