# Generated by Django 6.0.7 on 2026-08-23 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='validators',
            field=models.ManyToManyField(blank=True, related_name='documents_to_validate', to=settings.AUTH_USER_MODEL, verbose_name='validateurs'),
        ),
    ]
