# Generated by Django 6.0.7 on 2026-08-23 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_document_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('A_VALIDER', 'À valider'), ('VALIDE', 'Validé'), ('MODIFICATIONS_DEMANDEES', 'Modifications demandées'), ('REJETE', 'Rejeté'), ('PIECE_JOINTE', 'Pièce jointe')], default='PIECE_JOINTE', max_length=30, verbose_name='statut'),
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('MODIFICATIONS_DEMANDEES', 'Modifications demandées'), ('REJETE', 'Rejeté')], max_length=30, verbose_name='décision')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='le')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reviews', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.document', verbose_name='document')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
