# Generated by Django 6.0.7 on 2026-08-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_document_status_documentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deposit_decided',
            field=models.BooleanField(default=False, verbose_name='acompte : décision prise'),
        ),
    ]
