# Generated by Django 6.0.7 on 2026-08-24 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_documentversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='référence')),
                ('evenement', models.CharField(max_length=200, verbose_name='événement lié')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant du partenariat')),
                ('current_step', models.CharField(choices=[('CREATION', 'Création du dossier partenariat'), ('TRANSMISSION', 'Transmission au Head of Marketing'), ('DISCUSSIONS', 'Discussions, qualification, réunions et fiche signalétique'), ('ACCORD_PRINCIPE', 'Accord de principe'), ('PREPARATION_CONVENTION', 'Préparation de la convention'), ('SIGNATURE_CONVENTION', 'Envoi et signature de la convention'), ('PAIEMENT_INITIAL', 'Paiement initial si nécessaire'), ('SUPPORTS_COMMUNICATION', 'Mise au format et création des supports de communication'), ('DEPLOIEMENT', "Déploiement, installation et préparation de l'événement"), ('REALISATION', "Réalisation de l'événement"), ('BILAN', 'Bilan'), ('CLOTURE', 'Clôture')], default='CREATION', max_length=30, verbose_name='étape courante')),
                ('urgent', models.BooleanField(default=False, verbose_name='urgent')),
                ('requires_payment', models.BooleanField(default=False, verbose_name='paiement initial requis')),
                ('payment_received', models.BooleanField(default=False, verbose_name='paiement initial reçu')),
                ('convention_status', models.CharField(choices=[('NON_DEMARREE', 'Non démarrée'), ('EN_PREPARATION', 'En préparation'), ('ENVOYEE', 'Envoyée pour signature'), ('SIGNEE', 'Signée')], default='NON_DEMARREE', max_length=20, verbose_name='statut de la convention')),
                ('bilan_valide', models.BooleanField(default=False, verbose_name='bilan validé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partnership_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('head_marketing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='responsable marketing')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_dossiers', to='core.contact', verbose_name='partenaire')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='intitulé')),
                ('done', models.BooleanField(default=False, verbose_name='terminée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.partnershipdossier', verbose_name='dossier')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('kind', models.CharField(choices=[('SYSTEM', 'Système'), ('ACTION', 'Action')], default='SYSTEM', max_length=10, verbose_name='type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='le')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_timeline_entries', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.partnershipdossier', verbose_name='dossier')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
