# Generated by Django 6.0.7 on 2026-08-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_partnershipdossier_partnershiptask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.URLField(blank=True, verbose_name='lien'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='fichier'),
        ),
    ]
