# Generated by Django 6.0.7 on 2026-08-24 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_document_link_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.task', verbose_name='tâche'),
        ),
    ]
