# Generated by Django 6.0.7 on 2026-08-24 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_document_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.prestation', verbose_name='prestation'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='note',
            field=models.TextField(blank=True, verbose_name='consignes'),
        ),
    ]
