# Generated by Django 6.0.7 on 2026-08-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_document_prestation_prestation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipdossier',
            name='evenement_debut',
            field=models.DateField(blank=True, null=True, verbose_name="début de l'événement"),
        ),
        migrations.AddField(
            model_name='partnershipdossier',
            name='evenement_fin',
            field=models.DateField(blank=True, null=True, verbose_name="fin de l'événement"),
        ),
    ]
