# Generated by Django 6.0.7 on 2026-08-25 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_partnershipdossier_evenement_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PIN', 'Commentaire'), ('CIRCLE', 'Cercle')], max_length=10, verbose_name='type')),
                ('x', models.FloatField(verbose_name='position x (%)')),
                ('y', models.FloatField(verbose_name='position y (%)')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='largeur (%)')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='hauteur (%)')),
                ('comment', models.TextField(verbose_name='commentaire')),
                ('resolved', models.BooleanField(default=False, verbose_name='résolue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_annotations', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='core.documentversion', verbose_name='version')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
