# Generated by Django 6.0.7 on 2026-08-25 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_documentannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('method', models.CharField(choices=[('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money')], default='VIREMENT', max_length=20, verbose_name='mode de règlement')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('paid_at', models.DateTimeField(verbose_name='encaissé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.project', verbose_name='projet')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
