# Generated by Django 6.0.7 on 2026-08-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_projectpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CALL', 'Appel'), ('MEETING', 'Réunion'), ('LIVRAISON', 'Livraison')], max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('A_TRAITER', 'À traiter'), ('EN_COURS', 'En cours'), ('EN_VALIDATION_INTERNE', 'En validation interne'), ('EN_VALIDATION_CLIENT', 'En validation client'), ('EN_CORRECTION', 'En correction'), ('PRET_POUR_EXECUTION', 'Prêt pour exécution'), ('PRET_POUR_LIVRAISON', 'Prêt pour livraison'), ('LIVRE', 'Livré'), ('CLOTURE', 'Clôturé'), ('BLOQUE', 'Bloqué'), ('PERDUE', 'Perdue')], default='NOUVEAU', max_length=30, verbose_name='statut'),
        ),
    ]
