# Generated by Django 6.0.7 on 2026-09-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_event_event_type_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='original_starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date et heure initiale'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Accepté'), ('DECLINED', 'Décliné'), ('POSTPONED', 'Reporté')], default='ACCEPTED', max_length=20, verbose_name='statut'),
        ),
    ]
