# Generated by Django 6.0.7 on 2026-09-04 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_event_original_starts_at_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='mois')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='objectif (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='core.division', verbose_name='division')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='fixé par')),
            ],
            options={
                'ordering': ['-month', 'division__name'],
                'constraints': [models.UniqueConstraint(fields=('division', 'month'), name='unique_division_objective_per_month')],
            },
        ),
    ]
