# Generated by Django 6.0.7 on 2026-09-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_divisionobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='urgency',
            field=models.CharField(choices=[('HIGH', 'Élevée'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible')], default='LOW', max_length=10, verbose_name='urgence'),
        ),
    ]
